Create lots page
waterloo-rocketry/website-react pull request #69
Opened 2024-03-04 05:21 UTC by Redstone-ray

## Description
This is work in progress, I will update the team once its ready for review, just creating this so people know that it exists

2024-03-15 03:24 UTC, Redstone-ray commented
This is now ready for review @ManavToor @QuantumManiac @Darth-Raazi

2024-03-15 18:12 UTC, ManavToor requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/69)* status: all files reviewed, 23 unresolved discussions (waiting on @Darth-Raazi, @QuantumManiac, @Redstone-ray, and @shirleyfyx)

___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 50 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2DbPq4GfeLx25zwoh:-Nt2DbPq4GfeLx25zwoi:b-1tjzk9) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L50)):*
> ```JavaScript
>               to provide enhanced estimates of the rocket state during flight.
>               This was developed as a prototype for future active control
>               systems onboard the rocket. The other experiment consisted of yeast
> ```

I would change "The other experiment" to "The second experiment"
Also, you are switching from present to past tense halfway through the paragraph
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 64 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2EAwf9FLWiSiwHzPx:-Nt2EAwf9FLWiSiwHzPy:b1f935f) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L64)):*
> ```JavaScript
>               main parachute out of its bag, which inflates to a
>               partial state due to the presence of
>               a reefing line. At 1500 ft AGL, custom high-power
> ```

Maybe define what AGL stands for, most people reading this web page won't know.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 75 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2ETOH48w9YzOxYyq3:-Nt2ETOH48w9YzOxYyq4:b-yg1zkq) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L75)):*
> ```JavaScript
>               <br />
>               The system uses two COTS (Commercial Off-the-Shelf)
>               altimeters. A PerfectFlite StratoLoggerCF
> ```

This would be better: The system uses two COTS (Commercial Off-the-Shelf) altimeters: A PerfectFlite StratoLoggerCF and for increased reliability, a Featherweight Raven3.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 94 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2F5o668oxpcmk1p-w:-Nt2F5o668oxpcmk1p-x:b-p9iqg) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L94)):*
> ```JavaScript
>               board based on lessons learned throughout the previous years. In addition, this year,
>               new systems have been introduced and upgraded including a long-range live telemetry
>               radio system, in-flight camera systems, and an on-the-pad charging system.
> ```

you can remove the last three instances of the word "system"
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 97 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2FHlk3jJ2ed6Jq9OR:-Nt2FHlk3jJ2ed6Jq9OS:bma2ccw) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L97)):*
> ```JavaScript
>               <br />
>               <br />
>               The Electrical Ground Support Systems (EGSE) has also had substantial upgrades
> ```

I could be mistaken but would the acronym not instead be EGSS?

You use the word "system" a lot in this paragraph, maybe restructure it to be a little more sparing or find a suitable synonym
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 107 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2FuPC62-btLU3WnHq:-Nt2FuPC62-btLU3WnHr:b-kot5jp) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L107)):*
> ```JavaScript
>             </Content>
>             <Content title="NOSECONE">
>               Because of the possibility of going supersonic, a Von Kármán nosecone with a 4:1
> ```

Say: "With the possibility of"
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 108 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2G0E5-Hs1yAPgM01U:-Nt2G0E5-Hs1yAPgM01V:b-co8lvu) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L108)):*
> ```JavaScript
>             <Content title="NOSECONE">
>               Because of the possibility of going supersonic, a Von Kármán nosecone with a 4:1
>               fineness ratio, built from fiberglass was selected for LOTS. Two mold halves
> ```

say "was selected."

They already know we're talking about LotS
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 109 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2GBkT5U8UWRGXWhxj:-Nt2GBkT5U8UWRGXWhxk:b-4k9tyf) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L109)):*
> ```JavaScript
>               Because of the possibility of going supersonic, a Von Kármán nosecone with a 4:1
>               fineness ratio, built from fiberglass was selected for LOTS. Two mold halves
>               were formed with foam on a CNC router, and then joined during the layup
> ```

say "during a layup"
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 110 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2GHvx2yFLadK9S3z3:-Nt2GHvx2yFLadK9S3z4:b-mrwbu1) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L110)):*
> ```JavaScript
>               fineness ratio, built from fiberglass was selected for LOTS. Two mold halves
>               were formed with foam on a CNC router, and then joined during the layup
>               to form the complete nosecone shape. The nosecone was post-cured at 70 °C for
> ```

say "form a complete nosecone shape"
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 120 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2GfqeDptHdfheWcDn:-Nt2GfqeDptHdfheWcDo:b-ngo05b) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L120)):*
> ```JavaScript
>               The system is blow-down, utilizing the self pressurizing properties of nitrous oxide
>               to feed oxidizer into the injector. The oxidizer tank is made of 6061-T6 aluminium.
>               Due to increases in engine efficiency, the length of the oxidizer tank was reduced
> ```

Say "Thanks to increases in engine efficiency, the length of the oxidizer tank was able to be reduced"
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 124 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2H4JT-vG53OJNGc4g:-Nt2H4JT-vG53OJNGc4h:bbghwdk) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L124)):*
> ```JavaScript
>             </Content>
>             <Content title="COMBUSTION CHAMBER">
>               The combustion chamber comprises a structural pressure vessel containing
> ```

"comprises of a"
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 125 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2HABuDK_X5fCbT-F2:-Nt2HABuDK_X5fCbT-F3:b-5d5rsy) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPa [...]

2024-03-15 19:41 UTC, QuantumManiac submitted a review, later dismissed
Looks good from a code perspective. Please address the reviews on the actual content of the page and request re-review.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-:-Nt2cH9z8f9hROtP89V_:b-x818i8)* status: all files reviewed, 23 unresolved discussions (waiting on @Darth-Raazi, @Redstone-ray, and @shirleyfyx)



<!-- Sent from Reviewable.io -->

2024-03-18 23:59 UTC, jhschnel reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/69)* status: all files reviewed, 23 unresolved discussions (waiting on @Darth-Raazi, @ManavToor, @Redstone-ray, and @shirleyfyx)

___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 94 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2F5o668oxpcmk1p-w:-NtIoZqoBkLtbwxUFZky:b-2a6f5) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L94)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

you can remove the last three instances of the word "system"
</blockquote></details>

I disagree, I think having system indicates that the things listen aren't standalone items but rather multiple components working together. Personally, when reading the paragraph I don't think "system" seems overly repetitive or negatively impactful to the flow of the sentence
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 97 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2FHlk3jJ2ed6Jq9OR:-NtIpabE9t4Z2PT3qglx:b-v61zch) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L97)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

I could be mistaken but would the acronym not instead be EGSS?

You use the word "system" a lot in this paragraph, maybe restructure it to be a little more sparing or find a suitable synonym
</blockquote></details>

I believe the acronym is correct, but the system is actually called Electrical Ground Support Equipment
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 110 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2GHvx2yFLadK9S3z3:-NtIqjMCAI2ZVmNqCo_9:b-yaj80s) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L110)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

say "form a complete nosecone shape"
</blockquote></details>

I think "the" makes more sense here considering that it's not a general shape like a circle but rather a unique profile designed for this rocket alone
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 120 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2GfqeDptHdfheWcDn:-NtIrQm60kCeueCYfUbC:b-gw3eez) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L120)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

Say "Thanks to increases in engine efficiency, the length of the oxidizer tank was able to be reduced"
</blockquote></details>

I think this wording is clear enough and flows well, not sure I like the way "able to be" sounds
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 124 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2H4JT-vG53OJNGc4g:-NtIsW8378O9oGPJLntk:b-ev6rfu) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L124)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

"comprises of a"
</blockquote></details>

I think "is comprised of a" is a good in-between
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 140 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2HZzD-D5h-O26uy2t:-NtIvErGAk01yUhtis8a:b-opq3lq) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L140)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

say "to withstand the rocket's intense flight loads."
</blockquote></details>

"to withstand the immense flight loads of the rocket" removes the need to make the rocket possessive
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 142 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2HjVs1ditnsXA4G62:-NtIxIrJ2jmvfEzbcd1P:b3cwb7x) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L142)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

Grammatical errors in the last sentance
</blockquote></details>

How's "Other components, include machined aluminum couplers which are joined to
              the bodytubes using epoxy, and joined tohgether using a series of radial bolt rings."
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 152 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2IbLLEL04H-HxhWuA:-NtIycrEEDsrUFOYIiUm:b-64zfja) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L152)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

say "helped increase apogee"

say "In order to manufacture the fin can"
</blockquote></details>

Using "helped" makes it seem like the 3,000ft also came from other factors, is this stat not specifically about fin shape?
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 154 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2IpUQ3RQcbXAOnjJD:-NtIzF3R4josSXCkZvJG:bwcanil) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L154)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

Replace "Then" with "Secondly" or "Afterwards"

Replace "cut" with "cutout"
</blockquote></details>

Also included that they were cutout from a carbon fiber plate, I don't think cutout makes much sense there without the added context
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 158 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2J1slCJ6qeW69edNV:-NtIzyN5DEvRpRD_bFL8:b-f32097) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L158)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

Replace "which allows for" with "to allow for"
</blockquote></details>

Changed it to "which allowed for"


<!-- Sent from Reviewable.io -->

2024-03-19 20:04 UTC, ManavToor requested changes
Left some final reviews, just small things other than that LGTM

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-:-NtNJ3lG9jczMGh5O870:b-y26kzr)* status: 5 of 6 files reviewed, 23 unresolved discussions (waiting on @Darth-Raazi, @jhschnel, @Redstone-ray, and @shirleyfyx)

___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 120 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2GfqeDptHdfheWcDn:-NtNFer86gkOjvx44DaF:b-1ks39l) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L120)):*
<details><summary><i>Previously, jhschnel wrote…</i></summary><blockquote>

I think this wording is clear enough and flows well, not sure I like the way "able to be" sounds
</blockquote></details>

The "Due to" should definitely go, makes it sound like increasing the engine efficiency was a bad thing . Instead of "be able to", perhaps: "it was suitable to reduce the length of the oxidizer tank from previous..."
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 152 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2IbLLEL04H-HxhWuA:-NtNIdPHAus1w47IKKtw:b-avcz17) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L152)):*
<details><summary><i>Previously, jhschnel wrote…</i></summary><blockquote>

Using "helped" makes it seem like the 3,000ft also came from other factors, is this stat not specifically about fin shape?
</blockquote></details>

Agreed, ignore first statement, second is yet to be adressed


<!-- Sent from Reviewable.io -->

2024-03-19 21:37 UTC, Redstone-ray reviewed
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/69)* status: all files reviewed, 23 unresolved discussions (waiting on @Darth-Raazi, @ManavToor, and @shirleyfyx)

___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 50 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2DbPq4GfeLx25zwoh:-NtNbNYE44Lo6onOtpiv:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L50)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

I would change "The other experiment" to "The second experiment"
Also, you are switching from present to past tense halfway through the paragraph
</blockquote></details>

Done.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 64 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2EAwf9FLWiSiwHzPx:-NtNbP-2CKVJsdlmSKRS:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L64)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

Maybe define what AGL stands for, most people reading this web page won't know.
</blockquote></details>

Done.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 75 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2ETOH48w9YzOxYyq3:-NtNbPTI4w4m8Xx1TTIf:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L75)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

This would be better: The system uses two COTS (Commercial Off-the-Shelf) altimeters: A PerfectFlite StratoLoggerCF and for increased reliability, a Featherweight Raven3.
</blockquote></details>

Done.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 94 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2F5o668oxpcmk1p-w:-NtNbQv_CWjvDnIT_Xnv:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L94)):*
<details><summary><i>Previously, jhschnel wrote…</i></summary><blockquote>

I disagree, I think having system indicates that the things listen aren't standalone items but rather multiple components working together. Personally, when reading the paragraph I don't think "system" seems overly repetitive or negatively impactful to the flow of the sentence
</blockquote></details>

Done.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 97 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2FHlk3jJ2ed6Jq9OR:-NtNbUej4W5wXRqtzdPu:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L97)):*
<details><summary><i>Previously, jhschnel wrote…</i></summary><blockquote>

I believe the acronym is correct, but the system is actually called Electrical Ground Support Equipment
</blockquote></details>

Done.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 107 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2FuPC62-btLU3WnHq:-NtNbVgv4S8NppWzDg3E:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L107)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

Say: "With the possibility of"
</blockquote></details>

Done.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 108 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2G0E5-Hs1yAPgM01U:-NtNbW7q7uiP0j6kGcsm:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L108)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

say "was selected."

They already know we're talking about LotS
</blockquote></details>

Done.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 109 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2GBkT5U8UWRGXWhxj:-NtNbWYr3ze4Gghjspbe:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L109)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

say "during a layup"
</blockquote></details>

Done.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 110 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2GHvx2yFLadK9S3z3:-NtNbXKTBzahwzBWyBiS:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L110)):*
<details><summary><i>Previously, jhschnel wrote…</i></summary><blockquote>

I think "the" makes more sense here considering that it's not a general shape like a circle but rather a unique profile designed for this rocket alone
</blockquote></details>

Done.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 120 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2GfqeDptHdfheWcDn:-NtNcvw11B8NNvZiCSUV:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L120)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

The "Due to" should definitely go, makes it sound like increasing the engine efficiency was a bad thing . Instead of "be able to", perhaps: "it was suitable to reduce the length of the oxidizer tank from previous..."
</blockquote></details>

Done.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 124 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2H4JT-vG53OJNGc4g:-NtNcw_e8IWFSorLmLAN:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L124)):*
<details><summary><i>Previously, jhschnel wrote…</i></summary><blockquote>

I think "is comprised of a" is a good in-between
</blockquote></details>

Done.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 125 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2HABuDK_X5fCbT-F2:-NtNcx0O2dU9386crEW7:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L125)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

"and several other combustion devices."
</blockquote></details>

Done.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 138 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2HUMS7tG9ChwLdRiU:-NtNcxUJCMRSwD8iSHze:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L138)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

say "are used for their extremely"
</blockquote></details>

Done.
___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 140 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2HZzD-D5h-O26uy2t:-NtNcxzW4jydpwRz-UFR:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketP [...]

2024-03-19 21:39 UTC, Redstone-ray reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/69)* status: all files reviewed, 23 unresolved discussions (waiting on @Darth-Raazi, @ManavToor, and @shirleyfyx)



<!-- Sent from Reviewable.io -->

2024-03-19 22:05 UTC, jhschnel approved these changes

2024-03-19 23:51 UTC, ManavToor approved these changes
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/69)* status: all files reviewed, 23 unresolved discussions (waiting on @Darth-Raazi, @jhschnel, and @shirleyfyx)

___
*[`src/routes/rocketPages/LeviathanOfTheSky.jsx` line 120 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/69#-Nt2GfqeDptHdfheWcDn:-NtO6EDtAuSt5Li399Df:b-qs8yhx) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d95beae278a189278817653ecf9d70676f086fd/src/routes/rocketPages/LeviathanOfTheSky.jsx#L120)):*
<details><summary><i>Previously, Redstone-ray (Richard Ding) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not quite: 

"Thanks to increases in engine efficiency, the length of the oxidizer tank was reduced from previous iterations of the Kismet engine"


<!-- Sent from Reviewable.io -->

2024-03-20 00:19 UTC, merged